name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: m4asm-ubuntu
        path: build/m4asm

  build-msvc:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install PCRE
      run: vcpkg --triplet x64-windows install pcre

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: m4asm-windows
        path: build/Release/*

